// ABOUTME: Authenticity page explaining diVine's mission to preserve human creativity and limit AI content
// ABOUTME: Describes the restoration of original Vine content and commitment to human-made social media

import { Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Heart, Users, Camera, Shield, Sparkles, Archive, Video, Fingerprint } from 'lucide-react';
import { ZendeskWidget } from '@/components/ZendeskWidget';
import { MarketingLayout } from '@/components/MarketingLayout';

export function AuthenticityPage() {
  return (
    <MarketingLayout>
      <div className="container max-w-4xl mx-auto py-8 px-4 space-y-8">
      <ZendeskWidget />
      {/* Hero Section */}
      <div className="text-center space-y-4 py-8">
        <div className="flex justify-center">
          <Heart className="h-16 w-16 text-red-500 animate-pulse" />
        </div>
        <h1 className="text-5xl font-bold leading-tight">
          Social Media<br />
          By Humans,<br />
          For Humans
        </h1>
        <p className="text-2xl text-muted-foreground max-w-2xl mx-auto">
          In a world of AI-generated content, diVine is a sanctuary for authentic human creativity
        </p>
      </div>

      {/* The Vine Legacy */}
      <Card className="border-2 border-brand-green">
        <CardHeader>
          <CardTitle className="text-3xl flex items-center gap-3">
            <Video className="h-8 w-8 text-primary" />
            Building on the Original Vine
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-lg">
          <p>
            From 2013 to 2017, Vine was magic. Six seconds of pure, unfiltered human creativity.
            No algorithms deciding what you saw. No AI generating content. Just real people being
            creative, funny, weird, and wonderfully human.
          </p>
          <p>
            When Twitter shut down Vine, millions of moments of human creativity were nearly lost forever.
            <strong> That's why we restored them.</strong>
          </p>
          <div className="bg-brand-dark-green p-6 rounded-lg border border-brand-green">
            <p className="text-xl font-semibold text-brand-green">
              "Do it for the Vine!" wasn't just a meme—it was a celebration of authentic human expression.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Why Authenticity Matters */}
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl flex items-center gap-3">
            <Sparkles className="h-8 w-8" />
            Why Authenticity Matters Now More Than Ever
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-lg">
          <p>
            We're in the middle of an AI takeover of social media. New apps like Sora are entirely
            AI-generated. TikTok, YouTube, and Instagram are increasingly flooded with AI slop—videos
            that look real but were never captured by a camera, people who don't exist, scenarios
            that never happened.
          </p>
          <p>
            <strong>We're losing something precious: the ability to trust what we see.</strong>
          </p>
          <p>
            diVine is fighting back. We're not against AI existing—we're against AI <em>pretending</em> to be human.
            We're creating a space where human creativity is celebrated and protected, where you can trust
            that what you're watching was made by a real person with a real camera, not generated by an algorithm.
          </p>
          <div className="bg-brand-dark-green border-2 border-brand-green p-4 rounded-lg">
            <p className="font-semibold text-brand-off-white">
              The new "Vibes" social media apps are 100% AI-generated content. diVine is the opposite:
              we're building on the <em>original</em> authentic Vine, preserving real human creativity.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Our Commitment */}
      <div className="grid md:grid-cols-2 gap-6">
        <Card className="border-2 border-brand-green">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Archive className="h-6 w-6 text-primary" />
              Preserving the Past
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p className="text-muted-foreground">
              We've partnered with ArchiveTeam to restore and preserve original Vine content.
              These aren't just old videos—they're cultural artifacts of authentic human creativity
              from before the AI era.
            </p>
            <p className="font-semibold text-primary">
              Every restored Vine is a piece of genuine human expression, preserved for future generations.
            </p>
          </CardContent>
        </Card>

        <Card className="border-2 border-brand-green">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-6 w-6 text-primary" />
              Protecting the Future
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p className="text-muted-foreground">
              We use Proofmode technology to cryptographically verify that videos are captured by
              real cameras, not generated by AI. This raises the bar for authenticity and helps
              you trust what you're watching.
            </p>
            <p className="font-semibold text-primary">
              Every verified video carries proof that it was created by a human with a real device.
            </p>
            <p className="text-sm text-muted-foreground mt-2">
              <Link to="/proofmode" className="text-primary hover:underline font-semibold">
                Learn how Proofmode works →
              </Link>
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Proofmode - Human Rights Tech */}
      <Card className="border-2 border-brand-green">
        <CardHeader>
          <CardTitle className="text-3xl flex items-center gap-3">
            <Shield className="h-8 w-8 text-primary" />
            Using Human Rights Technology to Verify Authenticity
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-lg">
          <p>
            Proofmode was originally developed for human rights activists, journalists, and witnesses
            to prove that their documentation of events is authentic and unaltered. When someone is
            documenting human rights abuses or important events, the authenticity of their evidence
            can be a matter of life and death.
          </p>
          <p>
            We've brought this same technology to social media. Just as activists need to prove their
            videos are real, we all need ways to distinguish human-created content from AI-generated fakes.
          </p>
          <div className="bg-brand-dark-green p-6 rounded-lg border-2 border-brand-green space-y-4">
            <p className="font-semibold text-xl text-brand-off-white">
              Proofmode proves your videos are real by:
            </p>
            <div className="space-y-3">
              <div className="flex gap-3 items-start">
                <Camera className="h-5 w-5 mt-0.5 text-primary flex-shrink-0" />
                <div>
                  <p className="font-semibold">Capturing from Real Cameras</p>
                  <p className="text-sm text-brand-light-green">
                    Videos must be captured by your phone's camera, not uploaded from elsewhere or AI-generated
                  </p>
                </div>
              </div>
              <div className="flex gap-3 items-start">
                <Shield className="h-5 w-5 mt-0.5 text-primary flex-shrink-0" />
                <div>
                  <p className="font-semibold">Device Hardware Attestation</p>
                  <p className="text-sm text-brand-light-green">
                    Your phone's secure hardware proves the app and device are legitimate (not rooted/jailbroken)
                  </p>
                </div>
              </div>
              <div className="flex gap-3 items-start">
                <Fingerprint className="h-5 w-5 mt-0.5 text-primary flex-shrink-0" />
                <div>
                  <p className="font-semibold">Cryptographic Signatures</p>
                  <p className="text-sm text-brand-light-green">
                    Every video gets a unique digital signature proving it hasn't been edited or tampered with
                  </p>
                </div>
              </div>
            </div>
          </div>
          <p>
            This isn't just a policy saying "no AI allowed"—it's <strong>cryptographic proof</strong> that
            makes it technically difficult to pass off AI content as human-created. The same technology
            protecting human rights documentation now protects authentic social media.
          </p>
          <p className="pt-2">
            <Link to="/proofmode" className="text-primary hover:underline font-semibold text-lg">
              Learn more about Proofmode technology →
            </Link>
          </p>
        </CardContent>
      </Card>

      {/* Humans, Not Algorithms */}
      <Card className="border-2 border-brand-green">
        <CardHeader>
          <CardTitle className="text-3xl flex items-center gap-3">
            <Users className="h-8 w-8 text-primary" />
            Social Media By Humans, For Humans
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-lg">
          <p>
            diVine is built on these core principles:
          </p>
          <div className="space-y-4 mt-4">
            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-brand-dark-green flex items-center justify-center">
                <Camera className="h-5 w-5 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-xl mb-1">Real Cameras, Real Moments</h3>
                <p className="text-muted-foreground">
                  Videos should be captured by humans with real devices, not generated by AI.
                  We encourage direct recording and use Proofmode to verify authenticity.
                </p>
              </div>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-brand-dark-green flex items-center justify-center">
                <Heart className="h-5 w-5 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-xl mb-1">Human Expression Matters</h3>
                <p className="text-muted-foreground">
                  Every awkward moment, every genuine laugh, every creative idea—these are what make
                  content worth sharing. Imperfection is part of being human, and that's beautiful.
                </p>
              </div>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-brand-dark-green flex items-center justify-center">
                <Users className="h-5 w-5 text-primary" />
              </div>
              <div className="space-y-2">
                <h3 className="font-semibold text-xl mb-1">Community Over Algorithms</h3>
                <p className="text-muted-foreground">
                  Built on{" "}
                  <a href="https://nostr.org" rel="noopener noreferrer" className="text-primary hover:underline">
                    Nostr
                  </a>, a decentralized protocol where you own your content and connections.
                  No corporation can shut us down or take away your creative work.
                </p>
              </div>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-brand-dark-green flex items-center justify-center">
                <Shield className="h-5 w-5 text-primary" />
              </div>
              <div className="space-y-2">
                <h3 className="font-semibold text-xl mb-1">Digital Rights</h3>
                <p className="text-muted-foreground">
                  We're part of a broader movement fighting for user ownership, privacy, and control
                  of social media. Your data belongs to you, not corporations. Learn more at{" "}
                  <a href="https://rights.social" rel="noopener noreferrer" className="text-primary hover:underline">
                    Rights.Social
                  </a>.
                </p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* The Search for Authenticity */}
      <Card className="border-2 border-brand-green">
        <CardHeader>
          <CardTitle className="text-3xl">Our Search for Authenticity</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-lg">
          <p>
            We're not anti-technology. We love what technology can do. But we believe that social
            media should be a place where <strong>real people connect with real people</strong>.
          </p>
          <p>
            AI has its place—but that place isn't pretending to be human. Not on diVine.
          </p>
          <p>
            While platforms like TikTok, Instagram, and YouTube struggle with increasing AI slop,
            and new apps like Sora and "Vibes" embrace fully synthetic content, we're taking a
            different path: <strong>radical authenticity</strong>.
          </p>
          <div className="bg-brand-dark-green p-6 rounded-lg border-2 border-brand-green space-y-3">
            <p className="font-semibold text-xl text-brand-off-white">
              We're searching for authenticity by:
            </p>
            <ul className="space-y-2 list-disc list-inside text-brand-light-green">
              <li>Restoring and preserving original Vine content from the pre-AI era</li>
              <li>Using Proofmode to cryptographically verify new content is camera-captured</li>
              <li>Building on decentralized Nostr so no corporation can kill creative communities</li>
              <li>Celebrating human imperfection and genuine moments over polished AI-generated content</li>
              <li>Creating a space where trust is built through technology, not just policies</li>
              <li>Rejecting the AI slop that's drowning out human voices on mainstream platforms</li>
            </ul>
          </div>
        </CardContent>
      </Card>

      {/* What We're NOT */}
      <Card className="border-2 border-brand-green">
        <CardHeader>
          <CardTitle className="text-2xl">What diVine Is NOT</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-muted-foreground">
            We're not trying to ban AI from the internet. We're not saying AI is evil. We're not
            claiming to catch every single fake video.
          </p>
          <p className="font-semibold text-lg">
            We're simply creating a space where human creativity is valued, verified, and protected—a
            counterbalance to the wave of AI slop flooding major platforms and the new generation of
            fully synthetic social media apps.
          </p>
          <p className="text-muted-foreground">
            A place where "Do it for the Vine!" can live again—but this time, forever, and provably human.
          </p>
        </CardContent>
      </Card>

      {/* Join Us */}
      <Card className="border-2 border-primary">
        <CardHeader>
          <CardTitle className="text-3xl text-center">
            Join the Movement
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <p className="text-center text-lg text-muted-foreground">
            diVine is more than an app—it's a statement that human creativity matters.
            That authenticity is worth protecting. That social media can be by humans, for humans.
          </p>
          <div className="flex flex-wrap gap-4 justify-center">
            <Button size="lg" asChild>
              <Link to="/proofmode">
                <Shield className="h-5 w-5 mr-2" />
                Learn About Proofmode
              </Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link to="/about">
                <Heart className="h-5 w-5 mr-2" />
                Our Story
              </Link>
            </Button>
          </div>
          <div className="text-center pt-4">
            <p className="text-2xl font-bold text-primary">
              Do it for the Vine. Do it for humanity. Do it for diVine.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Learn More */}
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl">Learn More</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-muted-foreground">
            diVine is created by Rabble, building decentralized social media technologies
            and fighting for digital rights. Learn more at{" "}
            <a href="https://rabblelabs.com" rel="noopener noreferrer" className="text-primary hover:underline">
              RabbleLabs.com
            </a>{" "}
            or read about the history of social media at{" "}
            <a href="https://revolution.social" rel="noopener noreferrer" className="text-primary hover:underline">
              Revolution.Social
            </a>.
          </p>
        </CardContent>
      </Card>

      {/* Footer Quote */}
      <div className="text-center py-8 space-y-2">
        <p className="text-muted-foreground italic text-lg">
          "In an age of artificial everything, authenticity is revolutionary."
        </p>
        <p className="text-sm text-muted-foreground">
          — The diVine community
        </p>
      </div>
    </div>
    </MarketingLayout>
  );
}

export default AuthenticityPage;
