// ABOUTME: Page explaining the Human-Created certification badge
// ABOUTME: Describes criteria for displaying the badge and links to no-ai-icon.com

import { Brain, Shield, Video, ExternalLink } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { MarketingLayout } from '@/components/MarketingLayout';

export default function HumanCreatedPage() {
  return (
    <MarketingLayout>
      <div className="container max-w-4xl mx-auto px-4 py-8">
      <div className="space-y-8">
        {/* Header */}
        <div className="text-center space-y-4">
          <div className="flex items-center justify-center gap-3">
            <Brain className="h-12 w-12 text-purple-600" />
            <h1 className="text-4xl font-bold">Human-Created Content</h1>
          </div>
          <p className="text-xl text-muted-foreground">
            Certifying authentic, human-made videos on diVine Web
          </p>
        </div>

        {/* What is the Badge */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Brain className="h-5 w-5 text-purple-600" />
              What is the Human-Made Badge?
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              The <span className="font-semibold text-purple-600">Human-Made</span> badge certifies that a video
              was created by a real person, not generated by artificial intelligence. This badge helps you identify
              authentic content in an era where AI-generated videos are becoming increasingly common.
            </p>
            <p>
              We believe people should always be able to know if the content they consume is made by humans or
              artificial intelligence. This initiative is inspired by{' '}
              <a
                href="https://no-ai-icon.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary hover:underline inline-flex items-center gap-1"
              >
                no-ai-icon.com
                <ExternalLink className="h-3 w-3" />
              </a>
              , which provides free badges for creators to certify their work.
            </p>
          </CardContent>
        </Card>

        {/* When the Badge Appears */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Video className="h-5 w-5 text-purple-600" />
              When Does This Badge Appear?
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">1. Archived Videos (Automatic)</h3>
                <p className="text-muted-foreground">
                  All videos preserved from Internet Archive (2013-2017 era) automatically display this badge.
                  These videos were created before modern AI video generation existed, making them verifiably
                  human-created.
                </p>
              </div>

              <div>
                <h3 className="font-semibold mb-2">2. Creator-Claimed Content</h3>
                <p className="text-muted-foreground">
                  Content creators can add a <code className="text-sm bg-muted px-1 py-0.5 rounded">human-created</code>{' '}
                  tag to their video events to claim their work is 100% human-made. We trust creators to be honest
                  about their content's origins.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* ProofMode Integration */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5 text-purple-600" />
              How This Relates to ProofMode
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              The Human-Made badge complements our{' '}
              <span className="font-semibold text-green-600">ProofMode</span> verification system:
            </p>
            <ul className="space-y-2 list-disc list-inside text-muted-foreground">
              <li>
                <span className="font-semibold text-foreground">ProofMode</span> provides cryptographic proof that
                media is authentic and unmodified, with hardware-level attestation from mobile devices
              </li>
              <li>
                <span className="font-semibold text-foreground">Human-Made</span> certifies the content was created
                by humans, not AI-generated
              </li>
            </ul>
            <p>
              Together, these badges help build a more transparent and trustworthy platform where you can be confident
              about what you're watching.
            </p>
          </CardContent>
        </Card>

        {/* Verification with ProofMode */}
        <Card>
          <CardHeader>
            <CardTitle>Verification with ProofMode</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              To ensure content authenticity, new videos on Divine require{' '}
              <span className="font-semibold text-green-600">ProofMode verification</span>. ProofMode provides
              cryptographic proof that videos are captured directly from your device's camera, not AI-generated
              or uploaded from elsewhere.
            </p>
            <p>
              When you record a video with ProofMode enabled, your device creates cryptographic signatures
              and hardware attestations that prove the video's authenticity. This makes it technically difficult
              to pass off AI-generated content as human-made.
            </p>
            <div className="bg-muted p-4 rounded-lg">
              <p className="text-sm font-semibold mb-2">ProofMode provides:</p>
              <ul className="text-sm space-y-1 list-disc list-inside">
                <li>Device hardware attestation (proves real device, not emulator)</li>
                <li>Camera capture verification (must be recorded, not uploaded)</li>
                <li>Cryptographic signatures (detects any tampering)</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Community Reporting */}
        <Card>
          <CardHeader>
            <CardTitle>Community Reporting of AI Content</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              Divine empowers the community to report and label suspected AI-generated content. If you
              encounter a video that appears to be AI-generated, you can report it for review.
            </p>
            <p>
              Users can report content that shows signs of AI generation such as:
            </p>
            <ul className="space-y-2 list-disc list-inside text-muted-foreground">
              <li>Unnatural movements or physics defying reality</li>
              <li>Warped faces, hands with wrong number of fingers, or morphing objects</li>
              <li>Inconsistent lighting, shadows, or reflections</li>
              <li>Text that's garbled or nonsensical</li>
              <li>Background elements that appear or disappear</li>
            </ul>
            <p className="text-sm text-muted-foreground mt-4">
              <strong>Note:</strong> Reporting helps maintain content quality but doesn't automatically remove
              videos. Each report is reviewed, and repeated violations may result in content labeling or removal.
            </p>
          </CardContent>
        </Card>

        {/* Learn More */}
        <div className="flex justify-center">
          <Button asChild variant="outline" size="lg">
            <a
              href="https://no-ai-icon.com"
              target="_blank"
              rel="noopener noreferrer"
              className="gap-2"
            >
              Learn More at no-ai-icon.com
              <ExternalLink className="h-4 w-4" />
            </a>
          </Button>
        </div>
      </div>
    </div>
    </MarketingLayout>
  );
}
