// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:openvine/models/pending_upload.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PendingUploadAdapter());
    registerAdapter(UploadStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PendingUploadAdapter());
    registerAdapter(UploadStatusAdapter());
  }
}
